### ISSUE TITLE
Use of ckanext-cloudconnector

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/pandora#14]
https://github.com/DataShades/ckanext-cloudconnector

Any experience / view on this ext?

**Comment by florianm** [comment]
Haven't used it yet, as we're already on the AWS cloud. I've kept files close by on an EC2 volume, mounted inside the EC2 VM that runs the CKAN.

Pro cloudconnector: maybe S3 storage is cheaper than the EC2 SSD volume, haven't compared prices yet.

Pro EC2 SSD volume: as it's formatted with btrfs, the CKAN docker images behind datacats use btrfs natively (which is better than docker on aufs), and being a snapshotting fs, btrfs allows to create/restore internal snapshots easily. So as we're using the SSD and its btrfs fs for all other storage needs outside of CKAN's filestore (where cloudconnector comes in), I decided it's cleaner to keep everything in one place and go with the SSD. However, I'm open to discussion.
