### ISSUE TITLE
Presenting to Damian

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/pandora#19]

**Comment by florianm** [comment]
Talking points:

## catalogue-beta
- branding
- harvesting (CKAN federation, SLIP harvesting) - data flow diagram
- metadata schema - handouts of md schemas considered, mapping of our fields to their fields
- georeferencing - demo
- google analytics - show usage metrics
- static content - show static embedded page
- documentation - mention that there's up to date instructions to maintain current setup and replicate for other state govt agencies
- disaster recovery - mention that there's a way to backup all data, restore all data from backup (=DR)
- doi minting - explain data citation, mention that DOI minting creates automatically a free revenue stream of dataset citations for data custodians, driving data sharing
- public vs private CKAN - mention that private CKAN is important for user acceptance

## data science workbench
- assume your data is in CKAN - now what?
- interactive visualisation - show [timeseries explorer](http://rshiny.yes-we-ckan.org/shiny-timeseries/)
- automated data analysis - show data flow diagram of "CKAN CSV > R script > PDF > CKAN upload"
- reproducible research - show ckan-o-sweave (clean up template, fork, create an example report using example data on CKAN), demonstrate how Florian's MPA reports compile live
- version control - show data flow diagram of emailing MS word vs. git / ckan-o-sweave, mention disaster recovery on monday aug 10

## maintenance and support

Address the three pillars of successful information management as lessons learnt from 4 years of transformation at DPaW:
- **documentation** for users, maintainers, developers
- **training** of users, communication to stakeholders, presentations to groups
- **support** on the ground, one-on-one trouble-shooting

Address the communication model:

star diagram - 1:20 rule - one trained person can train and support 10 others
- One Keith/Florian-level maintainer can train 10..20 Keiths and Florians at other state govt departments to maintain their CKAN, analysis and report automation, and train CKAN and report editors
- One CKAN / report editor can support 10 to 20 colleagues to get their data and writing into CKAN and reports, respectively

There are 100+ departments, possibly 3-5 now and 20 within the next year ready to start using our CKAN / reporting solutions.
If time resources allow, Keith and Florian could train their counterparts in the early adopting departments and thus create a community of practice.

Lessons learnt from departments adopting CKAN, and their special requirements will drive the further evolution and organic, user-driven growth of data.wa.gov.au.

**Comment by keithmoss** [comment]
TODO Consider how catalogue harvesting is spelled out. There was that diagram...

**Comment by florianm** [comment]
![ckaaaan](https://cloud.githubusercontent.com/assets/762815/9267425/49938688-4281-11e5-895f-4266d954dc44.jpg)
