### ISSUE TITLE
Base CKAN install

### ISSUE THREAD

**Issue by florianm** [datawagovau/pandora#2]
Create AWS EC2 VM, install CKAN and dependencies. 
Depends: #1
Goal: vanilla CKAN install runs on data.wa.gov.au

**Comment by florianm** [comment]
vanilla CKAN runs on VM alpha on localhost:5500

**Comment by florianm** [comment]
Install interrupted by dockerhub registry API outage as per [dockerhub status page](https://status.docker.com/)

Status: install done for site alpha up to http://govhack2015.readthedocs.org/en/latest/2_CKAN_extensions/#enable-extensions-ckan-config

**Comment by keithmoss** [comment]
DNS entries created (internal and external):

54.153.249.73
catalogue-alpha.data.wa.gov.au
rstudio-alpha.data.wa.gov.au
rshiny-alpha.data.wa.gov.au

54.153.250.64
catalogue-beta.data.wa.gov.au
rstudio-beta.data.wa.gov.au
rshiny-beta.data.wa.gov.au

**Comment by florianm** [comment]
http://catalogue-alpha.data.wa.gov.au/
http://rstudio-alpha.data.wa.gov.au/
http://rshiny-alpha.data.wa.gov.au/

http://catalogue-beta.data.wa.gov.au/
http://rstudio-beta.data.wa.gov.au/
http://rshiny-beta.data.wa.gov.au/
