### ISSUE TITLE
Name resolution

### ISSUE THREAD

**Issue by florianm** [datawagovau/pandora#23]
Could we send a change request to IT for new DNS aliases:

*.alpha.data.wa.gov.au -> 54.153.249.73
*.beta.data.wa.gov.au -> 54.153.250.64

This allows us to spin up any number of subdomains on respective VMs without further DNS changes.

Use case: 
- example beta catalogues for DPaW / SRO to demonstrate harvesting
- addition of data science workbench servers (e.g. QGIS server)

**Comment by keithmoss** [comment]
Filed

**Comment by florianm** [comment]
http://catalogue.beta.data.wa.gov.au/
http://rstudio.beta.data.wa.gov.au/
http://rshiny.beta.data.wa.gov.au/
http://pycsw.beta.data.wa.gov.au/
http://qgis.beta.data.wa.gov.au/
