### ISSUE TITLE
Metadata schema

### ISSUE THREAD

**Issue by florianm** [datawagovau/pandora#3]
Discuss metadata schema

Combine from ANZLIC MCP v2 (marine), appropriate terrestrial, and DPaW fields

Keith says:
We will likely initially be adopting the metadata schema agreed by the other Australian CKAN portals & the Aus Govt Linked Data Working Group.

As a ‘quick’ first pass at getting a good metadata schema in place for data.wa.gov.au it does the job. Once it (and CKAN) is in place we’ll review its effectiveness, consider what to do with the old Interragator+ metadata catalogue WALIS has, and any metadata requirements/changes that come out of the work rebuilding SLIP.

https://toolkit.data.gov.au/index.php?title=Discovering_Metadata#Discovering_Metadata
https://data.gov.au/dataset/data-gov-au-metadata-and-other-schemas

For Florian – the modifications to their CKAN to support this live at

https://github.com/datagovau/ckanext-agls
https://github.com/datagovau/ckanext-datajson

**Comment by keithmoss** [comment]
- Assume using data.gov.au metadata schema
- Better understand technical requirements for National CKAN Search Metadata Alliance (@KM to send notes)
  - Consider impacts on catalogues that have custom schemas (like DPAW, SLIP)
  - Examine custom metadata fields WA might need/want
- Use SLIP/DPAW CKAN as an example of harvesting from one of many local WA data catalogues

**Comment by florianm** [comment]
"agency" fields as per https://data.gov.au/dataset/data-gov-au-metadata-and-other-schemas/resource/c79c5839-008e-4833-b469-3c550d38d05c should be implemented through custom organization schema

Custom organization schema pending https://github.com/open-data/ckanext-scheming/pull/29 pending https://github.com/open-data/ckanext-scheming/issues/72

**Comment by florianm** [comment]
Reopening issue to progress discussion around required metadata fields.
- starting point: [data.gov.au schema](https://data.gov.au/dataset/data-gov-au-metadata-and-other-schemas/resource/c79c5839-008e-4833-b469-3c550d38d05c)
- improvements: spatial form widget (some improvements pending), autocomplete for controlled voc like theme, place names (TODO), custom metadata schema for orgs
