### ISSUE TITLE
Enable registration

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/pandora#30]
No publishing rights by default. Require Super Admin to grant them publish rights.

Nice to have: CAPTCHA

**Comment by florianm** [comment]
I disabled user self-reg due to spam issues, but can bring it back with recaptcha (once their setup works, currently broken)

**Comment by keithmoss** [comment]
Recaptcha is broken, or the CKAN integration is?

**Comment by florianm** [comment]
recaptcha sign up just didn't work for me. ckan should be fine.

**Comment by florianm** [comment]
user self-reg re-enabled in docs and catalogue.alpha.data.wa.gov.au

**Comment by keithmoss** [comment]
``` html
<script src='https://www.google.com/recaptcha/api.js'></script>
<div class="g-recaptcha" data-sitekey="6LfC_A0TAAAAAF4k_wSLR8hfY2Fv30GRbmjRiXFu"></div>
```

**Comment by florianm** [comment]
nice, recaptcha works with private key and public key set
