### ISSUE TITLE
Implement data.gov.au metadata schema

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/pandora#32]
But via ckanext-schemeing

**Comment by florianm** [comment]
need some refinements around the dataset url, otherwise we're pretty much there

**Comment by keithmoss** [comment]
Schemeing depends on additions to spatial, can't be sent upstream in isolation.

**Comment by florianm** [comment]
pending rollout to instances on beta.data.wa.gov.au as soon as datacats/datapusher bug is fixed.
modified url fields as discussed.

**Comment by keithmoss** [comment]
Hmm...comparing to data.gov.au we seem to be missing these fields from the data.gov.au metadata schema (http://data.gov.au/dataset/data-gov-au-metadata-and-other-schemas):
- State: Active/Deleted
- Language: Free text (default: English)
- Data Status: Active/Inactive
- Update Frequency: Daily, ...
- Theme (aka AGIFT)
- Jurisdiction: Default to Western Australia, but allowing for overrides by local govt, et cetera

# Note to to self: Leave off for now
- Geospatial topic?
- Field(s) of Research

**Comment by florianm** [comment]
- state is an auto-field: deleted = invisible. I think this is cruft and we should omit it.
- update frequency esists
- Theme and other controlled voc keywords like geospatial topic and fields of research can be added if we have the required controlled vocabularies
- language was added
- organisation will get custom fields: homepage, jurisdiction, contact name and email, phone number

## requiring named vocabularies

like tags, require a web service endpoint for autocomplete
- theme
- geospatial topic
- fields of research
- spatial extent

**Comment by florianm** [comment]
custom groups in ckanext-scheming collide with customisations made by ckanext-hierarchy (nested orgs). will add discussed org metadata fields as standard extra fields as soon as available.

**Comment by keithamoss** [comment]
"Standard extra fields" in the sense of "on each datasets"?

**Comment by florianm** [comment]
Nope, as freeform extras on the default organization schema. Consistency
shouldn't  be an issue since we populate them all.

**Comment by keithamoss** [comment]
# Theme

Description: The [AGIFT](http://agift.naa.gov.au/) top level government function to which the dataset relates.

These should populate the dataset's group.

Business Support and Regulation
Civic Infrastructure
Communications
Community Services
Cultural Affairs
Defence
Education and Training
Employment
Environment
Finance Management
Governance
Health Care
Immigration
Indigenous Affairs
International Relations
Justice Administration
Maritime Services
Natural Resources
Primary Industries
Science
Security
Sport and Recreation
Tourism
Trade
Transport

**Comment by florianm** [comment]
That can be done via:
- ckan group
- custom dataset schema field with pre-populated options and select widget
- named voc with autocomplete widget (can have multiple)

**Comment by florianm** [comment]
Theme implemented as select
