### ISSUE TITLE
Move landgate.alpha.data.wa.gov.au to catalogue.beta.data.wa.gov.au

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/pandora#33]

**Comment by florianm** [comment]
will create a separate instance on beta - should there be a separate landgate catalogue, or is landgate public = data.wa.gov.au?

**Comment by keithmoss** [comment]
The latter: landgate public = data.wa.gov.au for now to keep things simple

**Comment by florianm** [comment]
landgate (= landgate org + slip datasets) are harvested into catalogue.beta.data.wa.gov.au.
This replaces the need for a separate, stand-alone public landgate ckan as discussed.
