### ISSUE TITLE
Theming CKAN

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/pandora#34]
Some polish required.

Highly desirable - Can we drop in the header markup from data.wa.gov.au so at least the top of the page matches between CKAN and data.wa.gov.au?

If not:
- [x] Change favicon to match data.wa.gov.au's
- [x] Add govt crest from data.wa.gov.au
- [x] Change catalogue name from "landgate.data.wa.gov.au" to "data.wa.gov.au"
- [x] Adopt data.wa.gov.au's tagline "Providing access to..." instead of "Public Data Catalogue"
- [ ] Adopt the same fonts as used data.wa.gov.au (headings = Open Sans, body text = Helvetica)

**Comment by keithmoss** [comment]
Related: Depending on outcome consider how easy it is for users to give feedback

**Comment by florianm** [comment]
Tag line "providing access to..." will almost certainly clash on smaller screens or resolutions, might need to move to the "intro" text in the main page section.

Fonts, logos, spacing should be fairly easy to emulate.

**Comment by keithmoss** [comment]
CKAN may be moving to Bootstrap 3 from 2.3. May collide if try and shove RSG template in.

To consider later.

**Comment by florianm** [comment]
done: position. remaining: fonts, favicon.

Existing theming was done as overrides to header template and CSS.

Fonts will require starting from the readysteadygov template, using that as base template for CKAN as and working backwards to un-break the layout and positioning.

Favicon is a simple fix, only requires one extra template override.

**Comment by florianm** [comment]
Is the theme as we currently have it (except the presumably major overhaul re fonts and spacing) good enough to soft-launch?
Then we could close this prio 1 and create a new task for the overhaul.

**Comment by keithmoss** [comment]
Great work, ta!

_stamp of approval_ Good to go :)
