### ISSUE TITLE
Implement metadata schema

### ISSUE THREAD

**Issue by florianm** [datawagovau/pandora#4]
Implement metadata schema defined in #3 using ckanext-scheming

**Comment by keithmoss** [comment]
_“our metadata is for discoverability and accessibility, not for listing every last possible facet of a dataset”_

**Comment by florianm** [comment]
first cut online at http://landgate.alpha.data.wa.gov.au/
- some fields need dev work (name-value autocompleting web service like tags for spatial extents and keywords)
- field `doi` is pending the doi plugin's minting magic
- we should discuss and iterate over labels, help text, fields

**Comment by florianm** [comment]
changes: https://github.com/datawagovau/ckanext-datawagovautheme/commit/553700ba00f2910761a248fc5614f870ef72b0a2

example: http://catalogue.alpha.data.wa.gov.au/dataset/test-data
