### ISSUE TITLE
Georeferencing requirements

### ISSUE THREAD

**Issue by florianm** [datawagovau/pandora#5]
Discuss georeferencing requirements

Currently available (A) or planned widgets for setting spatial extent of datasets:
- draw extent manually on map (A)
- set as convex hull from all attached geoJSON resources (with some effort)
- select from pre-defined list of extents (A)
- select from querying a name-to-extent resolving web service (will take effort)
- let users paste a valid GeoJSON geometry (A, standard CKAN-spatial feature)

**Comment by keithmoss** [comment]
- Sit and look at data.gov.au approach to georeferencing
  - Consider how to integrate custom regions and geo

**Comment by florianm** [comment]
ckanext-agls hacks together their own hard-coded metadata schema. 
Our setup uses the standard way of soft-configured custom md schemas using ckanext-scheming.

We can learn from agls about using custom tag vocabularies for "Geospatial Topic" and "Field(s) of Research".

We can do better with widgets for start.end date and geospatial extent.

**Comment by keithmoss** [comment]
data.gov.au's ckanext-algs Gazetteer API lookup only appears to return points, not polys/bboxes as assumed.

Ergo, going with @florianm's changes to ckanext-spatial to provide:
- On-map poly/bbox markup
- Choose from a pre-defined list
- Manually paste in GeoJSON

Future enhancements:
- Provide an API wrapper that exposes (a) the pre-defined list (soft config), and (b) the Gazetteer API (or other similar)
- Manually pasting GeoJSON or selecting a place from the list should render the shape on the map
- ??? @florianm What was the other enhancement we discussed?

**Comment by florianm** [comment]
infer extent as convex hull of all attached geojson resources
