### ISSUE TITLE
Enable user comments

### ISSUE THREAD

**Issue by florianm** [datawagovau/pandora#51]
ckanext-disqus

@keithm to provide disqus_url

**Comment by keithamoss** [comment]
Hmm looking at the [ckanext-disqus](https://github.com/ckan/ckanext-disqus) doco it sounds like it's optional and will just fallback to the current URL.

> Disqus will use window.location.href as the disqus_url. It is sometimes helpful, especially during development, to specify the base url for disqus to use instead.

Hm, but that in mind..maybe we want to use the non-beta URL so comments carry-over when we move from catalogue.beta.data.wa.gov.au to catalogue.data.wa.gov.au?

So try this and we'll see if it works:

```
disqus.disqus_url = catalogue.data.wa.gov.au
```

Hopefully it doesn't break anything in Disqus-land by using a URL that 404s.

**Comment by florianm** [comment]
done, working in beta and documented
