### ISSUE TITLE
Implement Georeferencing

### ISSUE THREAD

**Issue by florianm** [datawagovau/pandora#6]
Implement GR as discussed in #5

**Comment by keithmoss** [comment]
Fixing icons et cetera, small amount of work.

Est: Hour or two

**Comment by keithmoss** [comment]
Then clean code a little, and re-send as pull request upstream.

Est: 1 - 2 days

**Comment by florianm** [comment]
css fixed, looking good! ready to roll out to other instances than http://waitwaitboom.alpha.data.wa.gov.au/
